name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Rails ${{ matrix.rails }} on Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rails: "6.1"
            ruby: "3.2"

          - rails: "7.0"
            ruby: "3.2"
          - rails: "7.0b"
            ruby: "3.2"

          - rails: "7.1"
            ruby: "3.2"
          - rails: "7.1b"
            ruby: "3.2"
          - rails: "7.1.1"
            ruby: "3.2"

          - rails: "7.2"
            ruby: "3.3"

          - rails: "8.0"
            ruby: "3.4"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Gemfile
        run: echo $BUNDLE_GEMFILE

      - name: Ruby Version
        run: ruby --version

      - name: Run Tests
        run: bundle exec rake test
